# Generated by Django 3.0.8 on 2020-07-13 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_url', models.CharField(max_length=255, unique=True, verbose_name='Полный URL')),
                ('original_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Оригинальный ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_process', 'В обработке...'), ('done', 'Готов'), ('error', 'Ошибка'), ('ready', 'Ожидает')], default='new', max_length=10, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Плейлист',
                'verbose_name_plural': 'Плейлисты',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True)),
                ('original_id', models.BigIntegerField(null=True, unique=True, verbose_name='Оригинальный ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('permalink_url', models.CharField(max_length=255, null=True, verbose_name='Ссылка')),
                ('stream_url', models.CharField(max_length=255, null=True)),
                ('artwork_img_url', models.CharField(max_length=255, null=True)),
                ('waveform_img_url', models.CharField(max_length=255, null=True)),
                ('duration', models.BigIntegerField(default=0)),
                ('original_content_size', models.BigIntegerField(default=0)),
                ('genre', models.CharField(max_length=255, null=True, verbose_name='Жанр')),
                ('bpm', models.IntegerField(default=321, null=True)),
                ('release_year', models.IntegerField(null=True)),
                ('release_month', models.IntegerField(null=True)),
                ('release_day', models.IntegerField(null=True)),
                ('original_format', models.CharField(default='mp3', max_length=10, verbose_name='Формат')),
                ('counter', models.BigIntegerField(blank=True, default=0, verbose_name='Счетчик')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('playlist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Playlist', verbose_name='ID Плейлиста')),
            ],
            options={
                'verbose_name': 'Трэк',
                'verbose_name_plural': 'Треки',
                'ordering': ('-created_at',),
            },
        ),
    ]
