# Generated by Django 3.0.8 on 2020-07-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='download_counter',
            field=models.BigIntegerField(blank=True, default=0, verbose_name='Загрузили'),
        ),
    ]
