# Generated by Django 3.0.8 on 2020-07-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20200714_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=255, unique=True),
        ),
    ]
